Default: &defaults
  user: score
  password: score
  host: localhost
  database: score
  connections: 10

Development:
  <<: *defaults

Testing:
  database: score_test
  <<: *defaults

Staging:
  database: score_staging
  connections: 100
  <<: *defaults

Production:
  database: score_production
  connections: 100
  host: localhost
  <<: *defaults
